import Foundation
import AppKit

/// The "vault of mind" export: turn a region of the brain into a structured
/// markdown context pack, ready to paste at the top of a new LLM chat — the
/// "this is who I am" injection, distinct from relevance retrieval. Glia is
/// the surface for *choosing and seeing* what goes in; downstream tools
/// (MCP/skill) inject it.
enum ContextScope: String, CaseIterable, Identifiable {
    case collection  // the user's starred core-identity set (the "who I am")
    case selection   // the selected node + its connected neighborhood
    case identity    // curated identity pages (people/companies/concepts/originals/notes)
    case everything  // every page with an on-disk mirror file

    var id: String { rawValue }
    var label: String {
        switch self {
        case .collection: return "My collection (starred)"
        case .selection:  return "Selection + neighborhood"
        case .identity:   return "Identity (people, concepts, notes…)"
        case .everything: return "Everything on disk"
        }
    }
}

struct ContextBundle {
    let text: String
    let pageCount: Int
    /// Rough token estimate (~4 chars/token) for fitting a target window.
    var tokenEstimate: Int { max(0, text.count / 4) }

    /// The identity-content types — the substance of "who I am", excluding
    /// raw provenance dumps, atoms, and source snapshots.
    static let identityTypes: Set<String> =
        ["person", "company", "concept", "original", "note", "meeting"]

    /// Injection priority for the identity map (lower = leads the context):
    /// the self-page, then essays, then concepts/people, then the rest —
    /// so "who I am" front-loads the core rather than the freshest note.
    nonisolated static func identityRank(_ node: BrainNode) -> Int {
        let s = node.slug.lowercased()
        if s == "people-david" || s.hasSuffix("/david") { return 0 }   // the self-page
        if node.type == "original" || s.hasPrefix("originals/") { return 1 }  // essays
        if node.type == "concept" { return 2 }
        if node.type == "person" || node.type == "company" { return 3 }
        return 4
    }

    /// Build a bundle from the given nodes, reading each page's markdown from
    /// its source mirror. Pages with no on-disk file (atoms/raw) are skipped.
    @MainActor
    static func build(nodes: [BrainNode], header: String) -> ContextBundle {
        var parts: [String] = []
        parts.append("# \(header)")
        parts.append("<!-- Generated by Glia — a map of the mind for context injection. -->\n")
        var count = 0
        for node in nodes {
            guard let base = BrainLocation.sourceMirror(for: node.source) else { continue }
            let url = base.appendingPathComponent(node.slug + ".md")
            guard url.standardizedFileURL.path.hasPrefix(base.path),
                  let data = try? Data(contentsOf: url, options: .mappedIfSafe),
                  data.count < 400_000,
                  let raw = String(data: data, encoding: .utf8) else { continue }
            let body = MarkdownPreview.stripFrontmatter(raw)
                .replacingOccurrences(of: "<!--- gbrain:facts:begin -->", with: "")
                .replacingOccurrences(of: "<!--- gbrain:facts:end -->", with: "")
                .trimmingCharacters(in: .whitespacesAndNewlines)
            guard !body.isEmpty else { continue }
            parts.append("## \(node.displayTitle)  \n*\(node.type) · \(node.slug)*\n\n\(body)\n\n---")
            count += 1
        }
        return ContextBundle(text: parts.joined(separator: "\n"), pageCount: count)
    }

    @MainActor
    func copyToPasteboard() {
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(text, forType: .string)
    }

    @MainActor
    func save() {
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.plainText]
        panel.nameFieldStringValue = "brain-context.md"
        panel.message = "Save the context pack"
        if panel.runModal() == .OK, let url = panel.url {
            try? text.data(using: .utf8)?.write(to: url)
        }
    }
}
